.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maa-convert 1  "convert " 
.SH NAME
maa\-convert \- Convert file format between TOML, YAML and JSON
.SH SYNOPSIS
\fBmaa convert\fR [\fB\-f\fR|\fB\-\-format\fR] [\fB\-\-batch\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-q\fR|\fB\-\-quiet\fR]... [\fB\-\-log\-file\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIINPUT\fR> [\fIOUTPUT\fR] 
.SH DESCRIPTION
Convert file format between TOML, YAML and JSON
.PP
This command will convert a file from TOML, YAML or JSON format to another format. This is useful when you want to write your infrastructure configuration in TOML or YAML format, and use it in MaaCore, which only supports JSON format.
.PP
It may also be useful when you want to migrate your cli configuration from one format to another format.
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-format\fR \fI<FORMAT>\fR
Format of the output file, can be one of "toml", "yaml" and "json"

If not specified, the format will be guessed from the file extension of the output file. If output file is not specified, the output will be default to "json".
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
json
.IP \(bu 2
yaml
.IP \(bu 2
toml
.RE
.TP
\fB\-\-batch\fR
Enable batch mode

If there are some input parameters in the task file, some prompts will be displayed to ask for input. In batch mode, the prompts will be skipped, and parameters will be set to default values.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verbosity, repeat for more verbosity
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Decrease verbosity, repeat for more quiet
.TP
\fB\-\-log\-file\fR[=\fI<PATH>\fR]
Redirect log to file instead of stderr

If no log file is specified, the log will be written to $(maa dir log)/YYYY/MM/DD/HH:MM:SS.log.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIINPUT\fR>
Path of the input file
.TP
[\fIOUTPUT\fR]
Path of the output file, if not specified, the output will be printed to stdout
