.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH maa-self 1  "self " 
.SH NAME
maa\-self \- Manage maa\-cli self
.SH SYNOPSIS
\fBmaa self\fR [\fB\-\-batch\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-q\fR|\fB\-\-quiet\fR]... [\fB\-\-log\-file\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage maa\-cli self
.PP
This command is used to manage maa\-cli self and maa\-run. Note: If you want to install or update maa\-core and resource, please use maa\-cli install or maa\-cli update instead.
.SH OPTIONS
.TP
\fB\-\-batch\fR
Enable batch mode

If there are some input parameters in the task file, some prompts will be displayed to ask for input. In batch mode, the prompts will be skipped, and parameters will be set to default values.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verbosity, repeat for more verbosity
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Decrease verbosity, repeat for more quiet
.TP
\fB\-\-log\-file\fR[=\fI<PATH>\fR]
Redirect log to file instead of stderr

If no log file is specified, the log will be written to $(maa dir log)/YYYY/MM/DD/HH:MM:SS.log.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
maa\-self\-update(1)
Update maa\-cli self
